name: Backend CI (reusable)
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.11' # Corrected indentation

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 black pytest

      - name: Run flake8
        run: flake8 .

      - name: Black check (formatting)
        run: python -m black --check .

      - name: Run tests
        run: pytest -q
