name: Frontend CI (reusable)
on:
  workflow_call:
    inputs:
      node-version:
        
        required: false
        default: '20'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Run tests
        run: npm test -- --watchAll=false
