name: ML CI (reusable)
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.11'
      run-nbval:
        required: false
        default: 'false'

jobs:
  ml-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest nbval

      - name: Run unit tests
        run: pytest -q tests/

      - name: Notebook tests (optional)
        if: ${{ inputs.run-nbval == 'true' }}
        run: pytest --nbval notebooks/
